-- ==============================================================================
-- CORTA LA FRUTA - CONFIGURACION INICIAL DE BASE DE DATOS EN SUPABASE
-- ==============================================================================

-- 1. TABLA: menu_items (Productos del catálogo y modelos 3D)
CREATE TABLE IF NOT EXISTS public.menu_items (
  id TEXT PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  name TEXT NOT NULL,
  description TEXT DEFAULT '',
  price NUMERIC DEFAULT 0,
  scale NUMERIC DEFAULT 1,
  glburl TEXT,
  usdzurl TEXT,
  category TEXT DEFAULT 'Vasos de Fruta Cortada',
  image_urls TEXT[] DEFAULT '{}'
);

ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "menu_items_select_all" ON public.menu_items FOR SELECT USING (true);
CREATE POLICY "menu_items_insert_all" ON public.menu_items FOR INSERT WITH CHECK (true);
CREATE POLICY "menu_items_update_all" ON public.menu_items FOR UPDATE USING (true);
CREATE POLICY "menu_items_delete_all" ON public.menu_items FOR DELETE USING (true);

-- 2. TABLA: orders (Comandas de cocina y pedidos)
CREATE TABLE IF NOT EXISTS public.orders (
  id TEXT PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  table_name TEXT,
  items JSONB DEFAULT '[]'::jsonb,
  total NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'Pendiente'
);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "orders_select_all" ON public.orders FOR SELECT USING (true);
CREATE POLICY "orders_insert_all" ON public.orders FOR INSERT WITH CHECK (true);
CREATE POLICY "orders_update_all" ON public.orders FOR UPDATE USING (true);
CREATE POLICY "orders_delete_all" ON public.orders FOR DELETE USING (true);

-- 3. TABLA: service_requests (Llamados de mesa y pedidos de cuenta)
CREATE TABLE IF NOT EXISTS public.service_requests (
  id TEXT PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  table_name TEXT,
  type TEXT DEFAULT 'Llamar Mozo',
  status TEXT DEFAULT 'Pendiente'
);

ALTER TABLE public.service_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "service_requests_select_all" ON public.service_requests FOR SELECT USING (true);
CREATE POLICY "service_requests_insert_all" ON public.service_requests FOR INSERT WITH CHECK (true);
CREATE POLICY "service_requests_update_all" ON public.service_requests FOR UPDATE USING (true);
CREATE POLICY "service_requests_delete_all" ON public.service_requests FOR DELETE USING (true);

-- 4. TABLA: tables (Mesas y sectores)
CREATE TABLE IF NOT EXISTS public.tables (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  name TEXT NOT NULL,
  capacity INT DEFAULT 4,
  status TEXT DEFAULT 'Libre'
);

ALTER TABLE public.tables ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tables_select_all" ON public.tables FOR SELECT USING (true);
CREATE POLICY "tables_insert_all" ON public.tables FOR INSERT WITH CHECK (true);
CREATE POLICY "tables_update_all" ON public.tables FOR UPDATE USING (true);
CREATE POLICY "tables_delete_all" ON public.tables FOR DELETE USING (true);

-- 5. BUCKET DE STORAGE: menu-assets (para archivos .glb, .usdz e imagenes)
INSERT INTO storage.buckets (id, name, public)
VALUES ('menu-assets', 'menu-assets', true)
ON CONFLICT (id) DO UPDATE SET public = true;

CREATE POLICY "storage_select_menu_assets" ON storage.objects FOR SELECT USING (bucket_id = 'menu-assets');
CREATE POLICY "storage_insert_menu_assets" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'menu-assets');
CREATE POLICY "storage_update_menu_assets" ON storage.objects FOR UPDATE USING (bucket_id = 'menu-assets');
CREATE POLICY "storage_delete_menu_assets" ON storage.objects FOR DELETE USING (bucket_id = 'menu-assets');

-- 6. HABILITAR TIEMPO REAL (Realtime para cocina y salon)
ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;
ALTER PUBLICATION supabase_realtime ADD TABLE public.service_requests;
ALTER PUBLICATION supabase_realtime ADD TABLE public.menu_items;
ALTER PUBLICATION supabase_realtime ADD TABLE public.tables;

-- 7. PRODUCTOS INICIALES DE CORTA LA FRUTA
INSERT INTO public.menu_items (id, name, description, price, scale, glburl, category, image_urls)
VALUES
  ('p4', 'Especial Corta la Fruta 3D', 'Nuestra especialidad con kiwi, frutilla fresca, arándanos y frutas de estación. ¡Disponible en Realidad Aumentada 3D!', 4200, 1, '/uploads/halloween-fruit-platter.glb', 'Vasos de Fruta Cortada', ARRAY['/products/especial-corta-la-fruta.png']),
  ('p1', 'Vaso Sandía & Melón', 'Cortes frescos de sandía dulce y melón en su punto justo.', 2500, 1, NULL, 'Vasos de Fruta Cortada', ARRAY['https://images.unsplash.com/photo-1587049352847-4a222e784d38?auto=format&fit=crop&w=600&q=80']),
  ('p2', 'Vaso Mix Tropical', 'Combinación de mango, ananá, kiwi fresco y frutillas seleccionadas.', 3200, 1, NULL, 'Vasos de Fruta Cortada', ARRAY['https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80']),
  ('p3', 'Ensalada Clásica', 'Manzana, banana, naranja, uva y durazno en jugo natural de estación.', 3500, 1, NULL, 'Ensaladas de Frutas', ARRAY['https://images.unsplash.com/photo-1519996529931-28324d5a630e?auto=format&fit=crop&w=600&q=80']),
  ('p5', 'Yogur con Frutos Rojos', 'Yogur natural cremoso, granola horneada y mix de frutos rojos.', 4500, 1, NULL, 'Combinaciones con Yogur & Granola', ARRAY['https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=600&q=80']),
  ('p6', 'Yogur Tropical', 'Yogur natural, granola de miel, mango maduro y escamas de coco tostado.', 4500, 1, NULL, 'Combinaciones con Yogur & Granola', ARRAY['https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format&fit=crop&w=600&q=80'])
ON CONFLICT (id) DO NOTHING;

-- 8. MESAS INICIALES
INSERT INTO public.tables (name, capacity, status)
VALUES
  ('Mesa 1', 2, 'Libre'),
  ('Mesa 2', 4, 'Libre'),
  ('Mesa 3', 4, 'Libre'),
  ('Barra 1', 1, 'Libre')
ON CONFLICT DO NOTHING;
